# Generated by Django 6.0.4 on 2026-04-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shops', '0001_initial'),
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza_shops.pizzashopmodel'),
            preserve_default=False,
        ),
    ]
