# Generated by Django 6.0.4 on 2026-04-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizzamodel_pizza_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Tuesday', max_length=9),
            preserve_default=False,
        ),
    ]
