# Generated by Django 6.0.4 on 2026-04-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_alter_pizzamodel_name_alter_pizzamodel_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('-id',)},
        ),
    ]
