# Generated by Django 6.0.4 on 2026-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_alter_pizzamodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
