# Generated by Django 6.0.4 on 2026-04-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_alter_pizzamodel_options_pizzamodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzamodel',
            name='photo',
        ),
    ]
