# Generated by Django 6.0.4 on 2026-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_remove_pizzamodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
