# Generated by Django 6.0.4 on 2026-04-22 10:49

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_pizza_photo),
        ),
    ]
