# Generated by Django 6.0.4 on 2026-05-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0009_alter_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('-id',)},
        ),
    ]
