# Generated by Django 6.0.4 on 2026-04-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-id']},
        ),
    ]
