# Generated by Django 6.0.4 on 2026-05-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id']},
        ),
    ]
